### ISSUE TITLE
Redirect admin.insights posts to the main frontend

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/blog.ubuntu.com#265]
Currently if you get to a post on admin.insights it loads the old frontend. This should permanently redirect to the new insights frontend to remove duplicated content.

**Comment by anasereijo** [comment]
@anthonydillon is this still an issue?

**Comment by anthonydillon** [comment]
I don't this so, Google is not indexing these pages it seems and it is handy to see the posts and previews.
