### ISSUE TITLE
admin.insights.ubuntu.com wordpress "preview post" functionality

### ISSUE THREAD

**Issue by frankiegranato** [canonical-web-and-design/blog.ubuntu.com#273]
This task comes out of the related previous "investigation" task: https://app.zenhub.com/workspace/o/canonical-websites/insights.ubuntu.com/issues/93

Authors want to be able to see an accurate representation of their posts via the Preview function in Wordpress (currently authors can only preview their posts in the old insights site).

**Comment by anasereijo** [comment]
@anthonydillon  do you know if this is still required?

**Comment by anthonydillon** [comment]
Yes, but will take a backend to complete.

**Comment by anasereijo** [comment]
@nottrobin any thoughts?

**Comment by nottrobin** [comment]
Yep, true, it's base-squad work.

It's not in our plan for this roadmap cycle, and I doubt we can fit it in before May, but it's in our backlog.

**Comment by anasereijo** [comment]
Thanks @nottrobin. I will keep it open then.

**Comment by pmahnke** [comment]
Issue moved to [canonical-web-and-design/canonicalwebteam.blog #56](https://github.com/canonical-web-and-design/canonicalwebteam.blog/issues/56) via [**ZenHub**](https://www.zenhub.com/)
