### ISSUE TITLE
Workaround for code wraparound in insights

### ISSUE THREAD

**Issue by lamesdonner** [canonical-web-and-design/blog.ubuntu.com#352]
## Summary

For blogs with extensive code formatting, the default wraparound that Insights does makes it impossible to follow. Is there a way that we can fix insights going forward to allow the width of <pre> formatted content to be wider and be seen the way it's meant to?

Alternately, a workaround would be ideal.

Screenshots are a workaround in practice, but for replicating tutorials it's not very user friendly given you can't copy/paste (and you can't search it).

## Screenshot

For example: 

<img width="559" alt="screen shot 2018-05-08 at 12 42 28 pm" src="https://user-images.githubusercontent.com/30502149/39770538-4c672622-52bd-11e8-98d4-84db31aa31d1.png">

should look more like

<img width="518" alt="screen shot 2018-05-08 at 10 23 05 am" src="https://user-images.githubusercontent.com/30502149/39770553-562aed56-52bd-11e8-8992-9aaa3ad366d1.png">

**Comment by pmahnke** [comment]
it dead, closing (waves james!)
