### ISSUE TITLE
Images missing from imported design.canonical.com posts

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/blog.ubuntu.com#377]
Images are missing from most/all posts that were imported from design.canonical.com. For example:
- [Introducing the new Snapcraft branding](https://blog.ubuntu.com/2018/03/26/introducing-the-new-snapcraft-branding)
- [Cookie notification component](https://blog.ubuntu.com/2017/08/22/cookie-notification-component) (missing image just above the “The JavaScript” heading)
- [Vanilla Framework has a new website](https://blog.ubuntu.com/2017/08/14/vanilla-framework-has-a-new-website)

They are not missing from other posts. For example:
- [Design and web team summary – 4 June 2018](https://blog.ubuntu.com/2018/06/04/design-and-web-team-summary-4-june-2018)
- [Designing product page templates for ubuntu.com](https://blog.ubuntu.com/2017/10/10/designing-product-page-templates-for-ubuntu-com)
- [Simplifying local development: The ./run executable](https://blog.ubuntu.com/2017/07/05/simplifying-local-development-the-run-executable)

Part of the problem seems to be that the missing images are still requested from design.canonical.com. For example, “[Introducing the new Snapcraft branding](https://blog.ubuntu.com/2018/03/26/introducing-the-new-snapcraft-branding)” includes https://design.canonical.com/wp-content/uploads/3124/snapcraft_db_brandmark@4x.png which redirects to https://blog.ubuntu.com/topics/design/wp-content/uploads/3124/snapcraft_db_brandmark@4x.png which returns a 404 error. (I don’t know whether the image actually exists anywhere on blog.ubuntu.com.)

**Comment by anasereijo** [comment]
@anthonydillon how can we fix this? let me know if I can help

**Comment by anthonydillon** [comment]
This one is very tricky. I think the only way to fix them would be to see if IS have a backup of the design blog which we retired.

**Comment by matthewpaulthomas** [comment]
It’s possible that images were imported, along with the text, when design.canonical.com was imported into insights.ubuntu.com. If so, it’s just the `<img>` URLs that need changing. (And if not, that was a gobsmacking omission.) One way to determine this would be to read any code linked to from the issue/card/whatever that tracked the import work. Another way would be to look in the insights.ubuntu.com WordPress media library for images that have the same date as the design.canonical.com import.

I say “the insights.ubuntu.com WordPress media library” because blog.ubuntu.com posts from the Insights era are still embedding images from insights.ubuntu.com. (For example, [a photo of Munich from 2014](https://blog.ubuntu.com/2014/07/07/ubuntu-and-open-source-help-the-city-of-munich-save-millions).) If anyone ever retires the insights.ubuntu.com subdomain, or just decides to delete the “unused” i.u.c WordPress installation rather than patching the next vulnerability, or whatever, then all images from blog.ubuntu.com pre-2018 will suffer the same fate.

If images weren’t imported, and IS doesn’t have a backup, web.archive.org seems to have good coverage.

When the image URLs are changed, ideally they should be made relative, so that when the next migration happens (e.g. blog.ubuntu.com becomes ubuntu.com/news) everything doesn’t break again.

**Comment by anthonydillon** [comment]
The images are all back online. Thanks for reporting this issue.
