### ISSUE TITLE
Reduce the cache time to 5 minutes

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/blog.ubuntu.com#386]
Once we have #384, we should try reducing the cache time to only 5 minutes, as it should hopefully be able to handle it.

This should be done as part of this base squad epic: https://github.com/ubuntudesign/base-squad/issues/67

**Comment by nottrobin** [comment]
@b-m-f: How long is our default cache in the blog module?

**Comment by anasereijo** [comment]
@b-m-f any thoughts?

**Comment by nottrobin** [comment]
The default cache time in the blog module [is one hour](https://github.com/canonical-web-and-design/canonicalwebteam.blog/blob/master/canonicalwebteam/blog/wordpress_api.py#L11), we should probably shorten it.
