### ISSUE TITLE
L1TF post says “click here” but it does nothing

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/blog.ubuntu.com#391]
1\. If it’s still August 2018, go to [blog.ubuntu.com/](https://blog.ubuntu.com/) and scroll to the card for “Ubuntu updates for L1 Terminal Fault vulnerabilities”. If it isn’t still August, [search for “terminal fault”](https://blog.ubuntu.com/search?q=terminal+fault).

2\. Click on the text “click here”.

What happens: Nothing.

What should happen: either
- the words “click here” are not present, or
- clicking them does something.

This seems to be happening because
1\. [the post](https://blog.ubuntu.com/2018/08/14/ubuntu-updates-for-l1-terminal-fault-vulnerabilities) contains the phrase “click here” in its first line
2\. the post does not have a custom summary
3\. blog.ubuntu.com therefore uses the first ~30 words as a summary
4\. Any links in the summary are stripped, leaving the text behind.

So it could be fixed by:
1\. editing the post to use more accessible link text, or
2\. adding a custom summary to the post, or
4\. changing the summary code so that it doesn’t strip links.

**Comment by anasereijo** [comment]
@matthewpaulthomas I just checked the "click here" link and it's working. It opens [https://wiki.ubuntu.com/SecurityTeam/KnowledgeBase/L1TF](https://wiki.ubuntu.com/SecurityTeam/KnowledgeBase/L1TF)

**Comment by matthewpaulthomas** [comment]
Unfortunately this is still happening:
![blog ubuntu com#391-click-here](https://user-images.githubusercontent.com/19801137/54704238-4172c780-4b32-11e9-8ab7-d2d42f7fe5c4.gif)

Not a big deal, but really easy to fix for anyone who has permission to edit the post.

**Comment by solazio** [comment]
I fixed this by removing the first sentence and I will close this issue.
![image](https://user-images.githubusercontent.com/40214246/57300520-e63f6900-70ce-11e9-9d78-040c14434669.png)

**Comment by anasereijo** [comment]
@solazio please estimate this so we can get the points :)
