### ISSUE TITLE
Sharing links go to the homepage

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/blog.ubuntu.com#436]
## Summary
When sharing a post on Twitter the link contains the I'd which the platform does not understand.

## Process

- Go to a blog post
- click the Twitter share icon
- see the the preview link has `p=#####` instead of the post slug

## Current and expected result

The share content link should use the slug of the post instead of the id.

**Comment by anasereijo** [comment]
@anthonydillon is this something you can do?

**Comment by anthonydillon** [comment]
@anasereijo yes, could we add this to next iteration please.

**Comment by anasereijo** [comment]
please estimate
