### ISSUE TITLE
Shared URL can falsely claim that someone subscribed to the newsletter

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/blog.ubuntu.com#438]
1\. Go to [blog.ubuntu.com](https://blog.ubuntu.com/).
2\. Fill in and submit the “Newsletter signup” form.
3\. Continue reading the page.
4\. Share the page URL with someone.
5\. Have them visit the page.

What happens: The first thing they see is “Success: Thank you for subscribing! You will begin receiving emails as new content is posted”. Which isn’t true.

What should happen: They see the page as normal.

The form correctly uses `method="post"`, but the pages.canonical.com handler ends up redirecting to [https://blog.ubuntu.com/?newsletter=true](https://blog.ubuntu.com/?newsletter=true), with the parameter exposed in the URL.

Probably the correct approach is for pages.canonical.com to `post` back to blog.ubuntu.com too, so that `newsletter=true` isn’t exposed in the URL.

**Comment by pmahnke** [comment]
@matthewpaulthomas this will fixed when we move the site to u.c

you can see it here: https://www.ubuntu.com/download/desktop/thank-you
