### ISSUE TITLE
PrometheusLockTimeout: Timeout acquiring prometheus lock

### ISSUE THREAD

**Issue by tbille** [canonical-web-and-design/blog.ubuntu.com#469]
Notice the first time seen: 10-01-2019

Is it taliksker that has been updraded to v0.11.0 e few days before? or something else that has been modified recently?

https://sentry.is.canonical.com/canonical/blog-ubuntu-com/issues/748/

```
PrometheusLockTimeout: Timeout acquiring prometheus lock
  File "talisker/endpoints.py", line 269, in metrics
    data = collect_metrics()
  File "talisker/prometheus.py", line 169, in collect_metrics
    with try_prometheus_lock():
  File "python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "talisker/prometheus.py", line 82, in try_prometheus_lock_normal
    raise PrometheusLockTimeout('Timeout acquiring prometheus lock')

Failed to acquire prometheus lock to collect metrics
```

**Comment by tbille** [comment]
@anasereijo 	yes it still a valid we should add it to our backlog too to fix it.

**Comment by anasereijo** [comment]
@tbille I will move this issue to triaged then and maybe you can add to your backlog?

**Comment by pmahnke** [comment]
Issue moved to [canonical-web-and-design/base-squad #554](https://github.com/canonical-web-and-design/base-squad/issues/554) via [**ZenHub**](https://www.zenhub.com/)
