### ISSUE TITLE
Blog.ubuntu.com feed shows some weird item entry

### ISSUE THREAD

**Issue by MikkCZ** [canonical-web-and-design/blog.ubuntu.com#492]
## Summary
On https://blog.ubuntu.com/feed, the very first item looks like some kind of a spam post. It does not appear on the blog, only in the feed.

## Process
From the RSS feed, which is being consumed periodically by ubuntu.cz website to show latest blog posts, we have noticed a very weird first entry with non-latin characters. The link is dead.

## Current and expected result
I assume the entry simply should not be there...

I am attaching the current feed content as saved ~5 mintues ago - [feed.zip](https://github.com/canonical-websites/blog.ubuntu.com/files/2898368/feed.zip).

**Comment by pmahnke** [comment]
This is a duplicate of https://github.com/canonical-web-and-design/canonicalwebteam.blog/issues/49, thanks for filing, but closing this particular issue
