### ISSUE TITLE
[robotics] build cta to go on all robotics blog posts

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/blog.ubuntu.com#510]

**Comment by anasereijo** [comment]
This is ready to be built. Check design [here](https://github.com/canonical-web-and-design/blog.ubuntu.com/issues/518)

- strip class `is-deep`
- gradient: `background-image: linear-gradient(44deg, #171717 0%, #181818 9%, #262626 34%, #2D2D2D 67%, #383838 88%, #2E2E2E 100%, #393939 100%);`
- font `h3`
- [illustration](https://assets.ubuntu.com/v1/39ebd977-robot.svg)` witdh: 100px ` - hide it on mobile

**Comment by anasereijo** [comment]
@solazio this is ready to be built :) let me know if you have questions

**Comment by anasereijo** [comment]
@anthonydillon is this something @solazio can do?

**Comment by anthonydillon** [comment]
@anasereijo sure thing. Let me know if you need a hand.
