### ISSUE TITLE
blog.ubuntu.com does not have a colour assigned for people and culture category of post

### ISSUE THREAD

**Issue by campbieil** [canonical-web-and-design/blog.ubuntu.com#521]
## Summary
class="p-card__header--people-and-culture"
seems to be missing?

## Process
Go to blog.ubuntu.com and find a People and culture post
![Screenshot 2019-04-12 at 11 43 55](https://user-images.githubusercontent.com/230348/56031837-754ba200-5d18-11e9-9dcd-7c195932588d.png)

## Current and expected result
there should be a coloured banner at the top

## Screenshot

See step 2

**Comment by anasereijo** [comment]
Hi @campbieil thanks for opening this issue.

We are planning to create a permanent solution for this but in the meantime, this will be fixed [here](https://github.com/canonical-web-and-design/blog.ubuntu.com/issues/517)
