### ISSUE TITLE
Titles in simpligied Chinese mixes bold and regular font weights

### ISSUE THREAD

**Issue by pieqq** [canonical-web-and-design/blog.ubuntu.com#523]
## Summary

Recently, the Ubuntu blog started to post articles in non-English languages. We've seen for instance articles about 19.04 release in [Japanese](https://blog.ubuntu.com/2019/04/18/canonical%E3%80%81ubuntu-19-04%E3%82%92%E3%83%AA%E3%83%AA%E3%83%BC%E3%82%B9%E3%80%81-%E3%82%AA%E3%83%BC%E3%83%97%E3%83%B3%E3%82%A4%E3%83%B3%E3%83%95%E3%83%A9%E3%82%B9%E3%83%88%E3%83%A9%E3%82%AF) (although this article seems to have been taken down) or [simplified Chinese](https://blog.ubuntu.com/2019/04/20/ubuntu19-04-release-cn) (used in China).

I've noticed a rendering issue of the title in the blog post title of the simplified Chinese on Firefox, so I opened [an issue on WebCompat](https://github.com/webcompat/web-bugs/issues/29837).

After some investigation, it turns out this happens because the whole page is set in the HTML code to be in English (`<html lang="en">`, more information in [the Github issue](https://github.com/webcompat/web-bugs/issues/29837)). The lang attribute should be adapted depending on the content of the different HTML elements. (in the current case, since the web page is generally speaking in English, the `lang` attribute of the `html` element could remain `en`, but there should be a `lang` element for the article content itself with the appropriate language code.)

*Side note: would that make sense to have different translations of the same articles? I don't know if it's possible with the CMS used to power blog.ubuntu.com, but I know some blogging systems have this kind of features (e.g. [Nikola](https://www.getnikola.com/)). This would help to avoid having articles that are not relevant for some people.*

## Process

1. Go to [this blog post](https://blog.ubuntu.com/2019/04/20/ubuntu19-04-release-cn) using Firefox.

## Current and expected result

1. The title mixes bold and regular font weigths.

## Screenshot

[![Screenshot Description](https://webcompat.com/uploads/2019/4/7d47e0b4-1f48-4d44-a398-58512c578248-thumb.jpg)](https://webcompat.com/uploads/2019/4/7d47e0b4-1f48-4d44-a398-58512c578248.jpg)

**Comment by anthonydillon** [comment]
@pieqq thank you for bringing this to our attention. We provide a fix for this as soon as we can.

**Comment by b-m-f** [comment]
Just removed Chinese articles from the page. But setting the correct lang is definetely something to improve in https://github.com/canonical-web-and-design/cn.ubuntu.com

**Comment by anthonydillon** [comment]
@pieqq this is no longer an issue on the blog website as Chinese and Japanese content has been removed. Only English content is available via blog.ubuntu.com. For Chinese articles please visit [our Chinese blog](https://cn.ubuntu.com/blog) or [our Japanese blog](https://jp.ubuntu.com/blog).
