### ISSUE TITLE
Text overlapping on Perkuto email (mobile device)

### ISSUE THREAD

**Issue by WendyS1000** [canonical-web-and-design/blog.ubuntu.com#528]
Please see screengrab attached. It's from a Samsung on Gmail. 
![Ubuntu-Insights-mobile-display-issue](https://user-images.githubusercontent.com/49977866/57127044-10b7bc00-6d87-11e9-8605-bc9ce8020871.png)

**Comment by anthonydillon** [comment]
We have a new email template which Lucia is testing. It should be used for future newsletters

**Comment by anasereijo** [comment]
@anthonydillon will this happen in the new template? If not, I suggest closing this issue.
