### ISSUE TITLE
Strange bullet point before image

### ISSUE THREAD

**Issue by waynecrosby** [canonical-web-and-design/blog.ubuntu.com#540]
<img width="643" alt="Screenshot 2019-06-06 at 15 20 13" src="https://user-images.githubusercontent.com/42238722/59040563-ce463b00-886e-11e9-90a5-0979d32ff4c2.png">

## Summary

Bullet point is visible before the image in the main body of text

## Process

Go to this URL:
https://blog.ubuntu.com/2019/06/06/need-to-set-up-servers-in-remote-locations?_ga=2.174323874.1457196148.1559829582-91355398.1559829582

## Current and expected result

Is a visual thing, needs to be removed

## Screenshot

[if relevant, include a screenshot]

**Comment by pmahnke** [comment]
fixed

![image](https://user-images.githubusercontent.com/441217/59604263-96a78080-9103-11e9-942f-6f2f30b549fa.png)
