### ISSUE TITLE
Show more articles from author

### ISSUE THREAD

**Issue by yaili** [canonical-web-and-design/blog.ubuntu.com#542]
## Summary

I know I wrote 50+ articles. It's pretty sad that they're not shown anymore, as this was a bug that was fixed on the previous version of the design blog. Would be great to still have easy access to that archive. :( 

E.g. https://blog.ubuntu.com/author/inayaili-de-leon-persson

**Comment by anthonydillon** [comment]
@yaili thanks for filling this issue. Looks like the old blog did the same: https://admin.insights.ubuntu.com/author/inayaili-de-leon-persson/ but I agree should show all posts by the author. Will try and get this live shortly.

**Comment by yaili** [comment]
I meant design.canonical.com :)

**Comment by anthonydillon** [comment]
@yaili I have added a post view with pagination to the author view. You can find a demo link on the attached PR or just visit: 
https://blog-ubuntu-com-canonical-web-and-design-pr-543.run.demo.haus/author/inayaili-de-leon-persson

**Comment by yaili** [comment]
Very cool, thank you!
